# Use a imagem oficial do MySQL como base
FROM mysql:latest

# Defina variáveis de ambiente para o MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=nodedb
ENV MYSQL_PASSWORD=root

# Exponha a porta padrão do MySQL
EXPOSE 3306